### ISSUE TITLE
CO_322:0000674:EN_Ct_earplnt method abbreviation in variable name does not seem to match method

### ISSUE THREAD

**Issue by kadreher** [Planteome/CO_322-maize-traits#7]
Greetings.
The following variable is defined as being a calculation:
https://www.cropontology.org/terms/CO_322:0000674/EN_Ct_earplnt

It has the method:
https://www.cropontology.org/terms/CO_322:0000203/EN%20-%20Computation
http://www.cropontology.org/rdf/CO_322:0000203
with a formula:
Formula#Ears hvst / #Plts hvst

Therefore I would propose that the variable name should be:
EN_Cmp_earPlnt

Please let me know if you think that this variable name should be updated.

**Comment by elizabetharnaud** [comment]
Hi @kadreher : this is an obvious error indeed . Tom is following up but if you are interested to know how to do in the TD, contact us by mail.

**Comment by TomHazekam** [comment]
Hi @kadreher, I have made the change as you requested.
